### ISSUE TITLE
Would be nice to have some useful documentation..

### ISSUE THREAD

**Issue by ryan72804** [emotionLoop/visualCaptcha-packagist#4]
Would be nice to have some useful documentation..

**Comment by BrunoBernardino** [comment]
Indeed, it's in my TODO list.

You can look at https://github.com/emotionLoop/visualCaptcha-PHP for some documentation and integration notes

**Comment by ryan72804** [comment]
I've been looking at that. Still pretty confused about how to get it working on php/js

**Comment by BrunoBernardino** [comment]
It's a shame that many requests come by and are solved by email, but tell me what you need, I'll help you out.

That repo I mentioned above has that setup you're talking about and is a working example.

**Comment by ryan72804** [comment]
I've installed the backend via composer, and manually installed the frontend to its respective locations in our company code. After hooking up the js/css/images and initalizing the captcha, all that shows up is a the captcha as a blank div with only the css applied. Am I missing something here? Is it possible I installed the back-end in the wrong location?

**Comment by ryan72804** [comment]
Suppose I will just use a captcha that has explicit installation instructions..

**Comment by BrunoBernardino** [comment]
Sure. Sorry you couldn't figure it out. Let us know if you want to debug
and get it working.

A good starting point would be to check the routes called by the frontend
in the console, to see if it was requesting the images to the right URL or
not.

**Comment by BrunoBernardino** [comment]
Closed by https://github.com/emotionLoop/visualCaptcha-packagist/commit/cbc5cdf48c260c9852cd554359849041ec75a5e2
